// Authored Rebuild Sessions — generated from g4l_program_framework.json (program content as DATA).
import type { Asset } from '../types.ts';

export const REBUILD_SESSIONS: Asset[] = [
  {
    id: 'RBD-FST',
    title: 'The First Step Assessment',
    phase: 'rebuild',
    layer: 'Foundation',
    kind: 'session',
    order: 1,
    summary: 'Pick the movement you\'ll actually do, and set an honest starting line.',
    close_type: 'rep',
    produces: 'your vehicle + your starting baseline',
    steps: [
      {
        n: 1,
        title: 'Pick the vehicle',
        prompt: 'What\'s your vehicle — the movement you\'ll actually come back to?',
        input_type: 'choice',
        companion_frame: 'Time to move — but the best exercise isn\'t the \'optimal\' one, it\'s the one you\'ll actually do on a cold Wednesday. Walking is the most popular for a reason; cycling\'s right behind it.',
        probe: 'Be honest about your real life, not your ideal one. What fits the week you actually have?',
        contributes: 'none',
      },
      {
        n: 2,
        title: 'Where you\'re starting',
        prompt: 'How far or how long can you go today before it gets hard?',
        input_type: 'numbers',
        companion_frame: 'An honest baseline — how long can you go before it gets hard? No target, no judgment. We build from where you actually are, because that\'s the only place a foundation holds.',
        probe: 'Don\'t inflate it. The real number is the one we can build on.',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'That\'s your vehicle and your starting line. I\'ve put your starting line in your Playbook to keep or cut.',
      prompt: 'Want me to track this so you can watch it climb?',
      options: ['Yes', 'Not yet'],
      to_playbook: true,
    },
  },
  {
    id: 'RBD-INV',
    title: 'The Invisible Foundations',
    phase: 'rebuild',
    layer: 'Foundation',
    kind: 'session',
    order: 2,
    summary: 'Shore up one of the unseen basics that hold everything together.',
    close_type: 'goal',
    produces: 'your foundation pick for the week',
    steps: [
      {
        n: 1,
        title: 'The stuff nobody sees',
        prompt: 'Pick one invisible foundation to shore up this week — water, mobility, or breaking up sitting.',
        input_type: 'choice',
        companion_frame: 'The work that actually holds is invisible: hydration, a little mobility, not sitting for nine hours. Cutting your sedentary hours buys you benefits beyond your workout minutes.',
        probe: 'Which one, honestly, are you worst at? Start there.',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'Small and invisible, but it\'s the base the visible stuff stands on. I\'ve put your pick in your Playbook to keep or cut.',
      prompt: 'Make this a daily clip-in?',
      options: ['Yes', 'Not yet'],
      to_playbook: true,
    },
  },
  {
    id: 'RBD-SLP',
    title: 'Sleep & Recover',
    phase: 'rebuild',
    layer: 'Foundation',
    kind: 'session',
    order: 3,
    summary: 'Treat recovery as part of the work — and pull one lever to sleep better.',
    close_type: 'goal',
    produces: 'your one sleep lever',
    steps: [
      {
        n: 1,
        title: 'Recovery is the work',
        prompt: 'Honestly — how\'s your sleep right now?',
        input_type: 'writing',
        companion_frame: 'You don\'t get stronger during the effort — you get stronger during the recovery, when the body rebuilds. Skip it and you keep almost none of the gains.',
        probe: 'Past \'fine.\' How many real hours, and how often do you wake up?',
        contributes: 'none',
      },
      {
        n: 2,
        title: 'Pick one lever',
        prompt: 'Pick your one sleep lever for this week.',
        input_type: 'choice',
        companion_frame: 'We don\'t fix sleep all at once — we pull one lever. A fixed wind-down, screens off earlier, a darker room. Just one. The one you\'ll actually do tonight.',
        probe: 'Make it the easy one you\'ll actually do tonight.',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'Recovery isn\'t time off from the work — it is the work. I\'ve saved your sleep lever to your Playbook to keep or cut.',
      prompt: 'Run this lever every night this week?',
      options: ['I will', 'I\'ll try'],
      to_playbook: true,
    },
  },
  {
    id: 'RBD-FUEL',
    title: 'The Fuel Plan',
    phase: 'rebuild',
    layer: 'Structure',
    kind: 'session',
    order: 4,
    summary: 'Build a way of eating you have, not one you go on.',
    close_type: 'goal',
    produces: 'your keepable swap (and anti-crash line)',
    steps: [
      {
        n: 1,
        title: 'A diet you have',
        prompt: 'What\'s one swap you\'d actually keep — for good, not for a month?',
        input_type: 'writing',
        companion_frame: 'A diet isn\'t something you go on and white-knuckle until you fail — it\'s something you have. More real food, less added sugar and ultra-processed stuff. Not perfect. Sustainable.',
        probe: 'If it sounds like a punishment, you won\'t keep it. What\'s a swap you\'d barely miss?',
        contributes: 'playbook',
      },
      {
        n: 2,
        title: 'The thermostat',
        prompt: 'Write the one line that keeps you off the crash-diet cycle.',
        input_type: 'writing',
        companion_frame: 'Keeping weight off means moving your set point — slowly, like a thermostat. Crash diets fight it and lose. We move it instead, and it stays moved.',
        probe: 'Make it yours — the line you\'ll remember at week three when the scale stalls.',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'That\'s a way of eating you can actually keep. I\'ve put your swap and your line in your Playbook to keep or cut.',
      prompt: 'Start with this swap this week?',
      options: ['I\'m in', 'I\'ll try'],
      to_playbook: true,
    },
  },
  {
    id: 'RBD-MOVE',
    title: 'The Movement Menu',
    phase: 'rebuild',
    layer: 'Structure',
    kind: 'session',
    order: 5,
    summary: 'Build your real week of movement around the floor, not the ceiling.',
    close_type: 'goal',
    produces: 'your weekly movement plan (and a daily dose clip-in)',
    steps: [
      {
        n: 1,
        title: 'Build the week',
        prompt: 'Lay out your week — what days, what times does the movement happen?',
        input_type: 'writing',
        companion_frame: 'Aim for the floor first: about 150 minutes of moderate movement — roughly thirty minutes, five days. That\'s the floor that changes your health. Lock the floor before you chase the ceiling.',
        probe: 'Put it on real days at real times. When this week, specifically?',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'That\'s your week, on real days. I\'ve put it in your Playbook to keep or cut.',
      prompt: 'Turn on the daily movement check-in?',
      options: ['Yes', 'Not yet'],
      to_playbook: true,
    },
  },
];
