// Authored Reclaim Sessions — generated from g4l_program_framework.json (program content as DATA).
import type { Asset } from '../types.ts';

export const RECLAIM_SESSIONS: Asset[] = [
  {
    id: 'RCL-RDY',
    title: 'Reclaim Readiness',
    phase: 'reclaim',
    layer: 'Emergence',
    kind: 'session',
    order: 1,
    summary: 'Notice the reclaimed you starting to show up — and choose what to build next.',
    close_type: 'rep',
    produces: 'your Reclaim direction',
    steps: [
      {
        n: 1,
        title: 'Are you carrying it yet',
        prompt: 'Where have you caught a glimpse of the reclaimed you lately — even for a second?',
        input_type: 'writing',
        companion_frame: 'Reclaim isn\'t a finish line — it\'s the moment the person you\'ve been rebuilding starts showing up in the wider world. Are you starting to feel like the person on your list — even a little?',
        probe: 'Don\'t wait for the dramatic version. When did you last surprise yourself?',
        contributes: 'playbook',
      },
      {
        n: 2,
        title: 'Agency, not arrival',
        prompt: 'Which of the three do you most want to build next?',
        input_type: 'choice',
        companion_frame: 'Reclaiming means you\'ve got the wheel. Aging well comes down to meaningful activity, close relationships, and a sense of purpose. Reclaim goes after all three, deliberately.',
        probe: 'Pick the one that\'s been quietest lately. That\'s usually the one calling.',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'You\'re not arriving — you\'re taking the wheel. I\'ve put your direction in your Playbook to keep or cut.',
      prompt: 'Build toward that next?',
      options: ['Yes', 'Let me sit with it'],
      to_playbook: true,
    },
  },
  {
    id: 'RCL-SUC',
    title: 'Your Success Story',
    phase: 'reclaim',
    layer: 'Emergence',
    kind: 'session',
    order: 2,
    summary: 'Say the story of one thing you got back, in your own words.',
    close_type: 'reflect',
    produces: 'your success story (seed for the Legacy Letter)',
    steps: [
      {
        n: 1,
        title: 'Say it in your words',
        prompt: 'Tell the story of one thing you reclaimed — and what it felt like to notice it.',
        input_type: 'writing',
        companion_frame: 'Tell me the story of one thing you got back — out loud, in your own words. Not the metrics. What it felt like the first time you noticed the old you was back in the room.',
        probe: 'You gave me the what. Give me the moment — where were you when you felt it?',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'That\'s your story now, in your own words. I\'ve saved it to your Playbook to keep or cut.',
      prompt: 'Keep this one close?',
      options: ['Yes', 'Not yet'],
      to_playbook: true,
    },
  },
  {
    id: 'RCL-ADV',
    title: 'Adventure Planning',
    phase: 'reclaim',
    layer: 'Extension',
    kind: 'session',
    order: 3,
    summary: 'Put a measuring-stick event on the calendar, and back-plan the build.',
    close_type: 'goal',
    produces: 'your measuring-stick event (to the Reclaim List)',
    steps: [
      {
        n: 1,
        title: 'Put a measuring stick on the calendar',
        prompt: 'Name a real event or trip — with a date — that scares and excites you.',
        input_type: 'writing',
        companion_frame: 'A reclaimed identity needs a proving ground — something real on the calendar that scares and excites you. The thing that lets you say \'I did this.\' when it\'s done. Half the joy is the build-up.',
        probe: 'Put a date on it. A someday isn\'t a measuring stick — when?',
        contributes: 'goal',
      },
      {
        n: 2,
        title: 'Back-plan the build',
        prompt: 'Work backward — what does the first build week look like?',
        input_type: 'writing',
        companion_frame: 'Work backward from the date. What does your body need to handle that day, and what\'s the base you build in the quiet weeks before? You prepare so the day is a celebration, not a survival.',
        probe: 'Start with this week. What\'s the very first session toward it?',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'Now it\'s real — a date, and a path to it. I\'ve added the event to your Reclaim List and put the plan in your Playbook to keep or cut.',
      prompt: 'Add the event to your Reclaim List?',
      options: ['Yes', 'Not yet'],
      to_playbook: true,
    },
  },
  {
    id: 'RCL-BIG',
    title: 'Bigger World Audit',
    phase: 'reclaim',
    layer: 'Extension',
    kind: 'session',
    order: 4,
    summary: 'Find where your world went small, and push one edge back out.',
    close_type: 'goal',
    produces: 'the edge you\'ll push out this month',
    steps: [
      {
        n: 1,
        title: 'Widen the circle',
        prompt: 'Where has your world gone small — and what\'s one edge you\'d push back out this month?',
        input_type: 'writing',
        companion_frame: 'The Fade shrinks your world — the places you stopped going, the things you stopped saying yes to. Reclaim widens it back. Where has your world gone small? Then we pick one edge to push back out.',
        probe: 'Not the easy one. What\'s the yes that scares you a little?',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'That\'s the circle widening again — on purpose, by your hand. I\'ve put your edge in your Playbook to keep or cut.',
      prompt: 'Go after that edge this month?',
      options: ['I\'m in', 'I\'ll try'],
      to_playbook: true,
    },
  },
  {
    id: 'RCL-INV',
    title: 'Invitation Exercise',
    phase: 'reclaim',
    layer: 'Extension',
    kind: 'session',
    order: 5,
    summary: 'Bring someone with you — and find the words that actually land.',
    close_type: 'goal',
    produces: 'the message you\'ll send',
    steps: [
      {
        n: 1,
        title: 'Come do this with me',
        prompt: 'Who would you invite to do this with you?',
        input_type: 'writing',
        companion_frame: 'Here\'s how this stops being a solo act: you bring someone. The door opens through relationships, not credentials. Who would you say \'come do this with me\' to? Not to coach them — just to share the thing that gave you yourself back.',
        probe: 'Picture their face. Who came to mind first? Trust that.',
        contributes: 'playbook',
      },
      {
        n: 2,
        title: 'The words that matter',
        prompt: 'Write the message you\'d actually send them.',
        input_type: 'writing',
        companion_frame: 'The line that lands isn\'t \'you should exercise more.\' It\'s \'I know what you\'re capable of.\' That\'s the line that got said to me. That\'s the line I said to Gary.',
        probe: 'Lead with belief in them, not advice. What would make them feel seen?',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'That\'s how the comeback spreads — one person, one real message. I\'ve put it in your Playbook to keep or cut.',
      prompt: 'Send it this week?',
      options: ['I will', 'I\'ll try'],
      to_playbook: true,
    },
  },
  {
    id: 'RCL-SOC',
    title: 'Social Connection',
    phase: 'reclaim',
    layer: 'Legacy',
    kind: 'session',
    order: 6,
    summary: 'Find the place you actually belong — not just attend.',
    close_type: 'goal',
    produces: 'the place you\'ll show up',
    steps: [
      {
        n: 1,
        title: 'Find your people',
        prompt: 'Where\'s one place you could really belong — and show up for real?',
        input_type: 'writing',
        companion_frame: 'Belonging beats attending. Social support is one of the strongest predictors of change that sticks — and a real buffer against stress. Where do you belong, or want to? Not where you show up — where you\'re missed when you don\'t.',
        probe: 'Belonging, not attending. Where would they notice if you were gone?',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'That\'s the difference between attending and belonging — and belonging holds the whole thing up. I\'ve put your place in your Playbook to keep or cut.',
      prompt: 'Show up there this month?',
      options: ['Yes', 'I\'ll try'],
      to_playbook: true,
    },
  },
  {
    id: 'RCL-LEG',
    title: 'Legacy Letter',
    phase: 'reclaim',
    layer: 'Legacy',
    kind: 'session',
    order: 7,
    summary: 'Write it forward — and name the Loop.',
    close_type: 'reflect',
    produces: 'your Legacy Letter (the capstone keeper)',
    steps: [
      {
        n: 1,
        title: 'Write it forward',
        prompt: 'Write your letter — short is fine. What do you want them to know is still possible?',
        input_type: 'writing',
        companion_frame: 'Write a short letter to someone who\'ll read it later — a kid, a friend, the next person walking through the door you came through. What did you reclaim, and what do you want them to know is still possible in midlife?',
        probe: 'Write it to one real person, not \'whoever.\' Who needs to hear this from you?',
        contributes: 'playbook',
      },
      {
        n: 2,
        title: 'The Loop, named',
        prompt: 'What\'s the next thing the Loop is already calling you toward?',
        input_type: 'writing',
        companion_frame: 'The finish line moves. You\'ll reclaim these things, life will shift, the list will re-form, and you\'ll go again. That\'s not failure — that\'s the design. It\'s why it\'s Grinta for Life.',
        probe: 'You\'re not done — you\'re between laps. What\'s pulling at you next?',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'That\'s a letter forward and a name for what comes next. The work doesn\'t end — it loops, and you\'re stronger at the start of each one. This one, I\'d keep.',
      prompt: 'Ready to name the next lap?',
      options: ['Let\'s go', 'I need a minute'],
      to_playbook: true,
    },
  },
];
