// Authored Reconnect Sessions — generated from g4l_program_framework.json (the program content as
// DATA). The renderer reads these rows; this is content, not engineering. RCN-EXC (Identity
// Excavation) lives in registry.ts; the IDQ is a measurement; the Checkpoint is a ceremony.
import type { Asset } from '../types.ts';

export const RECONNECT_SESSIONS: Asset[] = [
  {
    id: 'RCN-BKQ',
    title: 'The Book Quiz',
    phase: 'reconnect',
    layer: 'Recognition',
    kind: 'session',
    order: 1,
    summary: 'Orient, and put a name to the feeling that brought you here.',
    close_type: 'reflect',
    produces: 'the moment you feel most like a stranger to yourself',
    steps: [
      {
        n: 1,
        title: 'Why you\'re here',
        prompt: 'Finish this line however it lands: \'Lately I feel most like a stranger to myself when ___.\'',
        input_type: 'writing_one_line',
        companion_frame: 'Before we start, a quick gut check — no studying, no wrong answers, just notice what comes up. There\'s usually one moment where the gap between who you are and who you feel like you\'ve become is loudest.',
        probe: 'Don\'t reach for the respectable answer. When does it actually hit — and where are you when it does?',
        contributes: 'playbook',
      },
      {
        n: 2,
        title: 'The Fade, named',
        prompt: 'Does \'the Fade\' fit what you just described? Tell me where it fits, and where it doesn\'t.',
        input_type: 'writing',
        companion_frame: 'Here\'s a word for that feeling: the Fade — the slow drift away from the person you used to be, built not from one disaster but from a hundred reasonable decisions. Most people never had a name for it. Now you do.',
        probe: 'Where doesn\'t it fit? The places it misses tell me your version — as useful as where it lands.',
        contributes: 'none',
      },
      {
        n: 3,
        title: 'What this is and isn\'t',
        prompt: 'Honestly — is that the kind of thing you actually want? Say it plainly.',
        input_type: 'writing',
        companion_frame: 'This isn\'t a program that tells you what to eat and tracks whether you obey. It\'s the opposite: you run your own comeback, and I hand you the tools and stay beside you the whole way.',
        probe: 'If there\'s a hesitation in there, name it. Better to say it now than carry it quietly.',
        contributes: 'none',
      },
    ],
    close: {
      companion: 'No grade here — just noticing. You\'ve named the feeling and given it a word, and that\'s where every comeback starts. I\'ve kept what surfaced in your Playbook to keep or cut.',
      prompt: 'Ready to look a little closer?',
      options: ['Yes', 'Give me a second'],
      to_playbook: true,
    },
  },
  {
    id: 'RCN-FDR',
    title: 'The Fade Doors',
    phase: 'reconnect',
    layer: 'Recognition',
    kind: 'session',
    order: 3,
    summary: 'Name the door (or doors) the Fade came in through.',
    close_type: 'reflect',
    produces: 'Your Doors (named on the dashboard)',
    steps: [
      {
        n: 1,
        title: 'How the gap opened',
        prompt: 'Which door sounds like yours? Name it — and what it actually was for you.',
        input_type: 'choice',
        companion_frame: 'Something usually opens the gap — rarely all at once. For most people it traces to one of eight doors: the Career Cliff, the Aging Parents, the Empty Nest, the Vanishing, the Body, the Diagnosis, the Marriage, the Loss.',
        probe: 'The door is a category; what happened to you specifically? Tell me your version.',
        contributes: 'your_doors',
      },
      {
        n: 2,
        title: 'More than one door',
        prompt: 'Is there a second door? If so, name it.',
        input_type: 'writing',
        companion_frame: 'Most people walked through more than one. If a second fits, name it — there\'s no prize for keeping it simple, and the truth helps me meet you where you actually are.',
        probe: 'Even if it feels smaller. Which other one\'s been quietly in the room?',
        contributes: 'your_doors',
      },
      {
        n: 3,
        title: 'Naming it back',
        prompt: 'Say it back in one sentence: \'The Fade came in through ___.\'',
        input_type: 'writing_one_line',
        companion_frame: 'That\'s a door a lot of good people have walked through — and most never had a name for it. Naming the door doesn\'t fix it; it just means we stop pretending it isn\'t there.',
        probe: 'Own it as yours — not a thing that happened to you, a door you walked through and can walk back out of.',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'Now your doors have names, and they\'re up on your dashboard. You can\'t close a door you won\'t look at. I\'ve put what surfaced in your Playbook to keep or cut.',
      prompt: 'Ready to dig for what\'s underneath?',
      options: ['Let\'s go', 'Give me a second'],
      to_playbook: true,
    },
  },
  {
    id: 'RCN-DFT',
    title: 'The Drift Quiz',
    phase: 'reconnect',
    layer: 'Excavation',
    kind: 'session',
    order: 5,
    summary: 'An honest read of what the Fade cost, and how far you\'ve drifted.',
    close_type: 'reflect',
    produces: 'your inventory + your honest distance',
    steps: [
      {
        n: 1,
        title: 'Be honest what it cost',
        prompt: 'Name three things the Fade cost you — be specific.',
        input_type: 'writing',
        companion_frame: 'Every life you build costs something. Be specific about what you traded away to get here: morning rides, deep friendships, the feeling of being in your body instead of trapped in your head. This isn\'t regret — it\'s inventory.',
        probe: 'Past the obvious. What\'s the quiet one you don\'t usually let yourself miss?',
        contributes: 'playbook',
      },
      {
        n: 2,
        title: 'How far, honestly',
        prompt: 'Honestly, how far are you from that version of you right now?',
        input_type: 'writing',
        companion_frame: 'On a normal week right now — how far are you from that buried version of you? A little dusty, or a stranger? There\'s no failing grade. The distance is just the starting line, and you can\'t close a gap you won\'t look at.',
        probe: 'Don\'t soften it to feel better. The real distance is the one we get to close.',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'That\'s your honest inventory — what it cost, and how far the drift ran. Not to sit in, to push off from. I\'ve put it in your Playbook to keep or cut.',
      prompt: 'Ready to see what\'s on the other side?',
      options: ['Yes', 'Give me a second'],
      to_playbook: true,
    },
  },
  {
    id: 'RCN-WIN',
    title: 'The Window',
    phase: 'reconnect',
    layer: 'Spark',
    kind: 'session',
    order: 6,
    summary: 'See the two Tuesdays — who you become if nothing changes, and if it does.',
    close_type: 'reflect',
    produces: 'the spark — your ordinary Tuesday, reclaimed',
    steps: [
      {
        n: 1,
        title: 'The window',
        prompt: 'Picture the Tuesday a year out if nothing changes. What does it look like?',
        input_type: 'writing',
        companion_frame: 'There\'s a window between who you are today and who you keep saying you\'ll be. Most people never look through it. Today you look: picture an ordinary Tuesday a year from now if nothing changes. Sit with that profile for a second.',
        probe: 'Not the disaster version — the ordinary one. How do you wake up, what do you reach for?',
        contributes: 'none',
      },
      {
        n: 2,
        title: 'The other window',
        prompt: 'Now the Tuesday where you did the work — what\'s different by 7am?',
        input_type: 'writing',
        companion_frame: 'Now the other Tuesday — same year out, but you\'ve been doing the work. What\'s different by 7am? Not the highlight reel. The ordinary stuff: how you wake up, what you reach for, how you move. That\'s the spark we\'re going to protect.',
        probe: 'Make it ordinary and real — not the medal, the morning.',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'That second Tuesday is the spark. Hold onto it — everything from here is about making it the real one. I\'ve saved it to your Playbook to keep or cut.',
      prompt: 'Ready to turn it into something you can chase?',
      options: ['Yes', 'Give me a second'],
      to_playbook: true,
    },
  },
  {
    id: 'RCN-WIN-LIST',
    title: 'Build Your Reclaim List',
    phase: 'reconnect',
    layer: 'Spark',
    kind: 'session',
    order: 7,
    summary: 'Turn the vision into specific, checkable things you want back.',
    close_type: 'goal',
    produces: 'your Reclaim List goals',
    steps: [
      {
        n: 1,
        title: 'Build the Reclaim List',
        prompt: 'List the specific things you want back — three to start.',
        input_type: 'writing',
        companion_frame: 'Turn that second Tuesday into real, specific things you want back. Riding before work without dreading it. Keeping up on the trail. Recognizing the person in the mirror. Give me a few — three to start, more if they keep coming. This becomes your Reclaim List.',
        probe: 'Make them things you\'d notice when they happen, not vague wishes. What\'s checkable?',
        contributes: 'reclaim_list',
      },
      {
        n: 2,
        title: 'Make each one checkable',
        prompt: 'Take one item and make it checkable — what would it look like in your week?',
        input_type: 'writing',
        companion_frame: 'Let\'s sharpen one. Say you want to \'feel like an athlete again\' — what would the Athlete actually be doing on a Tuesday that you\'re not doing now? We do this for each item, so every goal is something we can both see when it happens.',
        probe: 'If you couldn\'t tell whether you\'d done it, sharpen it. What\'s the version you\'d both see?',
        contributes: 'reclaim_list',
      },
    ],
    close: {
      companion: 'That\'s your Reclaim List — the whole point, in your own words. It lives on your dashboard, and we\'ll check things off it together as you win them back.',
      prompt: 'Lock these onto your dashboard?',
      options: ['Yes', 'Let me add more first'],
      to_playbook: true,
    },
  },
];
