// Authored Rewire Sessions — generated from g4l_program_framework.json (program content as DATA).
import type { Asset } from '../types.ts';

export const REWIRE_SESSIONS: Asset[] = [
  {
    id: 'RWR-DIS',
    title: 'The Disinformation Audit',
    phase: 'rewire',
    layer: 'Awareness',
    kind: 'session',
    order: 1,
    summary: 'Catch the comfortable lies your mind runs to keep you safe and small — and take them apart.',
    close_type: 'rep',
    produces: 'the member\'s true line (in their words)',
    steps: [
      {
        n: 1,
        title: 'The comfortable lie',
        prompt: 'Write the lie you tell yourself most — in its own words, the way your head actually says it.',
        input_type: 'writing_short',
        companion_frame: 'Your mind runs a quiet campaign to keep you comfortable — and comfortable, right now, means stuck. It tells you things that sound like facts: \'too late for me,\' \'I don\'t have the time,\' \'this is just what fifty looks like.\' Let\'s catch the loudest one.',
        probe: 'That\'s the cleaned-up version. What does it sound like at 6am when the alarm goes off? Say it rawer.',
        contributes: 'none',
      },
      {
        n: 2,
        title: 'Cross-examine it',
        prompt: 'Two columns: what\'s the real evidence this is true? And what\'s the evidence it\'s not?',
        input_type: 'writing_two_part',
        companion_frame: 'Now we put it on trial. A lie survives because no one ever asks it for evidence. What\'s the actual proof for it — and against it? \'Too old\' is a story; the people who started at your age and didn\'t stop are the counter-evidence.',
        probe: 'You found a lot against it and not much for it. So why have you been treating it like a verdict?',
        contributes: 'none',
      },
      {
        n: 3,
        title: 'Write the true line',
        prompt: 'Write your true line. One sentence. True enough that you\'d say it out loud.',
        input_type: 'writing_one_line',
        companion_frame: 'A lie you\'ve disproven still needs something to stand in its place. Not a slogan — something true you can stand behind on a bad day. Mine was \'I\'m out of shape, and I\'m starting anyway.\' Both halves true.',
        probe: 'If it sounds like a motivational poster, it won\'t hold — make it sound like you.',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'That\'s the audit. The lie won\'t vanish — but now you\'ve got a line to answer it with. I\'ve put your true line in your Playbook to keep or cut.',
      prompt: 'Next time the old line shows up, will you answer it with this one?',
      options: ['I will', 'I\'ll try'],
      to_playbook: true,
    },
  },
  {
    id: 'RWR-NUM',
    title: 'The Numbers Exercise',
    phase: 'rewire',
    layer: 'Awareness',
    kind: 'session',
    order: 2,
    summary: 'Pull your real numbers and look at them without flinching — a baseline, not a verdict.',
    close_type: 'rep',
    produces: 'your starting-line note (and baseline numbers)',
    steps: [
      {
        n: 1,
        title: 'Know your numbers',
        prompt: 'Gather your numbers and put them down — whatever you can get today.',
        input_type: 'numbers',
        companion_frame: 'Real change starts with the truth, and the truth here is numbers — not how you feel, not a guess. Pull what you can: weight, resting heart rate, blood pressure. We\'re not here to judge them. We\'re here to face them.',
        probe: 'If one made you wince, that\'s the one that matters most. Don\'t round it kinder than it is.',
        contributes: 'tracker_optional',
      },
      {
        n: 2,
        title: 'Look without flinching',
        prompt: 'Write one sentence you want to remember about this starting line.',
        input_type: 'writing_one_line',
        companion_frame: 'Now look at them straight, without the flinch and without the story. This isn\'t your verdict — it\'s your starting line, and every starting line is a place to push off from.',
        probe: 'Make it the version that steadies you, not the one that shames you.',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'These are your baseline now — not a grade, a starting line. I\'ve dropped your note into your Playbook to keep or cut.',
      prompt: 'Want me to track any of these so you can see them change?',
      options: ['Yes', 'Not yet'],
      to_playbook: true,
    },
  },
  {
    id: 'RWR-FOO',
    title: 'The Food Relationship Assessment',
    phase: 'rewire',
    layer: 'Awareness',
    kind: 'session',
    order: 3,
    summary: 'See what food is really doing for you — then try one new lens.',
    close_type: 'goal',
    produces: 'your food reframe (in their words)',
    steps: [
      {
        n: 1,
        title: 'Fuel, not comfort',
        prompt: 'When you eat when you\'re not hungry — what\'s it really for?',
        input_type: 'writing',
        companion_frame: 'Quick gut check, no shame. When you eat and you\'re not hungry, what\'s it actually doing for you — comfort, reward, boredom? Naming food\'s real job is the first move toward changing it.',
        probe: 'Go past \'stress.\' What\'s the feeling right before you reach for it?',
        contributes: 'none',
      },
      {
        n: 2,
        title: 'One reframe',
        prompt: 'Write your food reframe — \'Food is ___ for the ___ I\'m reclaiming.\'',
        input_type: 'writing_one_line',
        companion_frame: 'Try this lens for one meal today: food as fuel for the person you\'re reclaiming — not a reward you earned, not a punishment. A new relationship with food gets built one plate at a time.',
        probe: 'Name the actual identity — \'for the cyclist,\' \'for the dad who keeps up.\'',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'That\'s a new deal with food — a lens you can carry. I\'ve put your reframe in your Playbook to keep or cut.',
      prompt: 'Use this lens at your next meal?',
      options: ['I\'m in', 'I\'ll try'],
      to_playbook: true,
    },
  },
  {
    id: 'RWR-VIS',
    title: 'The Visualization Workshop',
    phase: 'rewire',
    layer: 'Visualization',
    kind: 'session',
    order: 4,
    summary: 'Use the trick athletes use — rehearse the hard thing before it happens.',
    close_type: 'rep',
    produces: 'your rehearsed win (in their words)',
    steps: [
      {
        n: 1,
        title: 'Why this isn\'t woo',
        prompt: 'Pick the moment you most want to handle better — the 6am alarm, the hill, the room you walk into. Name it.',
        input_type: 'writing_short',
        companion_frame: 'Athletes picture the shot before they take it because the brain barely tells a vividly imagined action from a real one — same pathways fire. It\'s a skill, not a vibe, and you can build it.',
        probe: 'Make it specific and real — a moment you\'ll meet this week, not a someday.',
        contributes: 'none',
      },
      {
        n: 2,
        title: 'Rehearse the feeling',
        prompt: 'Run it, then write what it felt like to get through it.',
        input_type: 'writing',
        companion_frame: 'Run the tape for sixty seconds. Don\'t picture the outcome — feel it. The effort, the breath, standing a little taller after. That rehearsal is what you draw on when the real moment comes.',
        probe: 'You described what happened. What did it feel like in your body when you didn\'t quit?',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'You just practiced winning before it happened. I\'ve saved what it felt like to your Playbook to keep or cut.',
      prompt: 'Run this once more before the moment this week?',
      options: ['Yes', 'I\'ll try'],
      to_playbook: true,
    },
  },
  {
    id: 'RWR-STK',
    title: 'The Self-Talk Audit',
    phase: 'rewire',
    layer: 'Hardiness',
    kind: 'session',
    order: 5,
    summary: 'Catch how you talk to yourself, and rewrite one line true-but-forgiving.',
    close_type: 'rep',
    produces: 'your reframed line (in their words)',
    steps: [
      {
        n: 1,
        title: 'Catch the voice',
        prompt: 'Write the harshest thing you say to yourself when you mess up — word for word.',
        input_type: 'writing',
        companion_frame: 'For a day, listen to how you talk to yourself when you slip. Would you say it to a friend you respect? Most of us run an inner coach we\'d fire on the spot. You can\'t change a voice you haven\'t heard.',
        probe: 'That\'s the printable version. What\'s the actual word you use? Write the real one.',
        contributes: 'none',
      },
      {
        n: 2,
        title: 'Reframe one line',
        prompt: 'Rewrite your line — true, but on your side.',
        input_type: 'writing_one_line',
        companion_frame: 'Take that harsh line and rewrite it true but forgiving. \'I always quit\' becomes \'I\'ve stopped before, and I\'m here again.\' Forgiving yourself isn\'t going soft — it\'s how the change survives a bad day.',
        probe: 'If it sounds fake-positive, you won\'t believe it. Keep the truth in it.',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'You just fired the coach you\'d never have hired. I\'ve put your reframed line in your Playbook to keep or cut.',
      prompt: 'Catch yourself once this week and use the new line?',
      options: ['I will', 'I\'ll try'],
      to_playbook: true,
    },
  },
  {
    id: 'RWR-FST',
    title: 'The False Start Protocol',
    phase: 'rewire',
    layer: 'Hardiness',
    kind: 'session',
    order: 6,
    summary: 'Decide your clip-back-in move now, while it\'s calm — before the slip.',
    close_type: 'rep',
    produces: 'your clip-back-in move (in their words)',
    steps: [
      {
        n: 1,
        title: 'Setbacks are built in',
        prompt: 'What does your slip usually look like? How does a good run fall apart?',
        input_type: 'writing',
        companion_frame: 'Setbacks are part of the process, not proof you failed. The people who make it aren\'t the ones who never slip — they\'re the ones who don\'t let a slip become a slide. Let\'s build your plan for the slip before it happens.',
        probe: 'Name the real pattern, not the excuse. What\'s the first domino?',
        contributes: 'none',
      },
      {
        n: 2,
        title: 'Your clip-back-in move',
        prompt: 'Write your clip-back-in move — the one tiny thing that means you\'re back.',
        input_type: 'writing_one_line',
        companion_frame: 'Write your return move while it\'s calm: the smallest action that counts as clipping back in after a missed day. Not a redemption arc — one rep. Decide it now, so the next-day you doesn\'t have to negotiate.',
        probe: 'Smaller. Make it so easy you can\'t talk yourself out of it on the worst day.',
        contributes: 'playbook',
      },
    ],
    close: {
      companion: 'Now the slip has a plan, and a plan beats willpower. I\'ve put your move in your Playbook to keep or cut.',
      prompt: 'If you miss this week, will you run this move?',
      options: ['I will', 'I\'ll try'],
      to_playbook: true,
    },
  },
];

// v2.3 CONVERSATIONAL Rewire — the guided Phase flow (Decision: 3 Sessions + the Checkpoint; the old Atlas Rewire
// Sessions above are parked for potential later integration). Route-backed (no step player) → the forecast links to
// /rewire/… and treats them as built. W1 unlocks after the Reconnect ceremony; W2/W3/Checkpoint follow in order.
export const REWIRE_V23: Asset[] = [
  {
    id: 'RWR-W1', title: 'The Disinformation Audit', phase: 'rewire', layer: 'Affirmation', kind: 'session', order: 1,
    summary: 'Catch the comfortable lies your mind runs — and write the true lines that answer them.',
    close_type: 'rep', produces: "the member's true lines (in their words)", route: '/rewire/{memberId}/w1', gating: 'reconnect_checkpoint_passed',
  },
  {
    id: 'RWR-W2', title: 'The Visualization Workshop', phase: 'rewire', layer: 'Visualization', kind: 'session', order: 2,
    summary: 'Build a vivid picture of where you’re headed — the one the old voice can’t compete with.',
    close_type: 'rep', produces: "the member's image (in their words)", route: '/rewire/{memberId}/w2',
  },
  {
    id: 'RWR-W3', title: 'The False Start Protocol', phase: 'rewire', layer: 'Focus', kind: 'session', order: 3,
    summary: 'Build the plan for the day it goes sideways — Redirect, Reframe, Restart.',
    close_type: 'rep', produces: "the member's recovery protocol (in their words)", route: '/rewire/{memberId}/w3',
  },
  {
    id: 'RWR-CHK', title: 'The Rewire Checkpoint', phase: 'rewire', layer: 'Checkpoint', kind: 'checkpoint', order: 4,
    summary: 'A read on the commitment you built — and the close of the Phase.',
    close_type: 'milestone', earns: 'rewire-milestone', route: '/rewire/{memberId}/checkpoint',
  },
];
