// The Daily Beat library — 70 standalone reflections re-cut from the Beat Registry (see
// G4L_Daily_Beat_Build_Spec). Member-facing content as DATA; the panel renders from here.
// 'Daily Beat' is the single sanctioned member-facing use of 'Beat' (rhythm sense).

export type ReflectionPhase = 'reconnect' | 'rewire' | 'rebuild' | 'reclaim' | 'universal';
export type Reflection = {
  id: string;
  text: string;
  phase: ReflectionPhase;
  source: string; // the asset it came from (traceability)
  theme: string;
  keepable: boolean;
};

export const REFLECTIONS: Reflection[] = [
  { id: 'RCN-BKQ-01', text: 'There\'s a moment most days when you feel most like a stranger to yourself. Noticing exactly when it hits — that isn\'t weakness. It\'s the start of the way back.', phase: 'reconnect', source: 'Book Quiz', theme: 'the fade', keepable: true },
  { id: 'RCN-BKQ-02', text: 'The Fade: the slow drift away from the person you used to be — built not from one disaster but from a hundred reasonable decisions. Naming it doesn\'t fix it. It means you stop pretending it isn\'t there.', phase: 'reconnect', source: 'Book Quiz', theme: 'the fade', keepable: true },
  { id: 'RCN-BKQ-03', text: 'This was never about a program that tells you what to eat and checks whether you obeyed. It\'s the opposite — you run your own comeback. The tools are in your hands, and you\'re not doing it alone.', phase: 'reconnect', source: 'Book Quiz', theme: 'agency', keepable: true },
  { id: 'RCN-IDQ-01', text: 'An honest read of where you\'re starting doesn\'t need studying for, and there\'s no score to pass. A few of the answers will sting. That sting is the point — it\'s the gap, finally in view.', phase: 'reconnect', source: 'IDQ', theme: 'honesty', keepable: true },
  { id: 'RCN-IDQ-02', text: 'How far you\'ve drifted comes down to four things: your body, your sense of self, the people around you, and where you\'re headed. It\'s a slow, honest measure — real change in who you are doesn\'t jump week to week.', phase: 'reconnect', source: 'IDQ', theme: 'identity', keepable: true },
  { id: 'RCN-IDQ-RETAKE', text: 'Real change in who you are doesn\'t move week to week — it moves over seasons. When you measure again, let it be still if it\'s still. Slow and real beats fast and fake.', phase: 'reconnect', source: 'IDQ', theme: 'patience', keepable: true },
  { id: 'RCN-FDR-01', text: 'The gap rarely opens all at once. For most people it traces to a single door — a career cliff, an aging parent, an empty nest, a diagnosis, a loss. Knowing which one is yours is the start of walking back through it.', phase: 'reconnect', source: 'Fade Doors', theme: 'doors', keepable: true },
  { id: 'RCN-FDR-02', text: 'Most people walked through more than one door. There\'s no prize for keeping your story simple — the truth is what lets you be met where you actually are.', phase: 'reconnect', source: 'Fade Doors', theme: 'doors', keepable: true },
  { id: 'RCN-FDR-03', text: 'The door you came through is one a lot of good people have walked through — and most never had a name for it. Naming it doesn\'t fix it. It means you stop pretending it isn\'t there.', phase: 'reconnect', source: 'Fade Doors', theme: 'doors', keepable: true },
  { id: 'RCN-EXC-01', text: 'What did twelve-year-old you do when nobody was watching — the thing you lost track of time in, before mortgages and meetings? The sport, the instrument, the thing you quit because it \'wasn\'t practical.\' That\'s probably your vein of gold.', phase: 'reconnect', source: 'Identity Excavation', theme: 'excavation', keepable: true },
  { id: 'RCN-EXC-02', text: 'Your mind will lie to you — too old, too far gone, too busy. Your identity knows better. It isn\'t gone; it\'s buried under decades of being responsible. Who were you, underneath all the roles?', phase: 'reconnect', source: 'Identity Excavation', theme: 'identity', keepable: true },
  { id: 'RCN-EXC-03', text: 'You\'ve spent years as a supporting character in everyone else\'s story — the company\'s, the kids\', the partner\'s. All worthy. None of them yours. You deserve a story that\'s yours too. That isn\'t selfish. It\'s overdue.', phase: 'reconnect', source: 'Identity Excavation', theme: 'identity', keepable: true },
  { id: 'RCN-EXC-04', text: 'Put a word on the person you\'re bringing back — the Athlete, the Builder, the Friend. It doesn\'t have to be perfect. It has to be true enough to aim at.', phase: 'reconnect', source: 'Identity Excavation', theme: 'identity', keepable: true },
  { id: 'RCN-DFT-01', text: 'Every life you build costs something — the morning rides, the deep friendships, the feeling of being in your body instead of trapped in your head. Naming what you traded isn\'t regret. It\'s inventory.', phase: 'reconnect', source: 'Drift Quiz', theme: 'honesty', keepable: true },
  { id: 'RCN-DFT-02', text: 'The distance between you and the buried version of you isn\'t a failing grade. It\'s a starting line. And you can\'t close a gap you won\'t look at.', phase: 'reconnect', source: 'Drift Quiz', theme: 'honesty', keepable: true },
  { id: 'RCN-WIN-01', text: 'There\'s a window between who you are today and who you keep saying you\'ll be. Picture an ordinary Tuesday a year from now if nothing changes. Most people never look. Looking is the first brave thing.', phase: 'reconnect', source: 'Window Exercise', theme: 'vision', keepable: true },
  { id: 'RCN-WIN-02', text: 'Now the other Tuesday — a year out, but you\'ve done the work. Not the highlight reel; the ordinary stuff. How you wake up, what you reach for, how you move. That\'s the spark worth protecting.', phase: 'reconnect', source: 'Window Exercise', theme: 'vision', keepable: true },
  { id: 'RCN-WIN-03', text: 'The future you want isn\'t a feeling — it\'s specific. Riding before work without dreading it. Keeping up on the trail. Recognizing the person in the mirror. The clearer you name what you want back, the more real it becomes.', phase: 'reconnect', source: 'Window Exercise', theme: 'vision', keepable: true },
  { id: 'RCN-WIN-04', text: '\'Feel like an athlete again\' stays a wish until you ask: what would the Athlete actually be doing on a Tuesday that you\'re not doing now? A goal you can picture is a goal you can reach.', phase: 'reconnect', source: 'Window Exercise', theme: 'goals', keepable: true },
  { id: 'RWR-DIS-01', text: 'Your mind runs a quiet campaign to keep you comfortable: \'too late for me,\' \'I don\'t have time,\' \'this is just what fifty looks like.\' Naming the loudest lie is how you stop obeying it.', phase: 'rewire', source: 'Disinformation Audit', theme: 'mindset', keepable: true },
  { id: 'RWR-DIS-02', text: 'Take the lie to court. \'Too old\' is a story; the people who started at your age and didn\'t stop are the counter-evidence. Most of these don\'t survive being looked at directly.', phase: 'rewire', source: 'Disinformation Audit', theme: 'mindset', keepable: true },
  { id: 'RWR-DIS-03', text: 'Replace the lie with one true sentence you can stand behind — not a slogan, something you believe. \'I\'m out of shape and I\'m starting anyway.\' That\'s the line you come back to when the old one gets loud.', phase: 'rewire', source: 'Disinformation Audit', theme: 'mindset', keepable: true },
  { id: 'RWR-NUM-01', text: 'Real change starts with an honest look at where you actually are — not a guess, not how you feel. Facing the numbers isn\'t judgment. It\'s information you can finally use.', phase: 'rewire', source: 'Numbers Exercise', theme: 'honesty', keepable: true },
  { id: 'RWR-NUM-02', text: 'A baseline you can see without looking away is a starting line, not a verdict. That clarity is what makes it possible to set goals that mean something.', phase: 'rewire', source: 'Numbers Exercise', theme: 'honesty', keepable: true },
  { id: 'RWR-VIS-01', text: 'Athletes picture the shot before they take it because the brain barely tells a vividly imagined action from a real one — the same pathways fire. Rehearsing the hard thing is a skill, and you can build it.', phase: 'rewire', source: 'Visualization Workshop', theme: 'mindset', keepable: true },
  { id: 'RWR-VIS-02', text: 'Run the tape for sixty seconds: finishing a hard effort, the confidence after, standing a little taller. Don\'t picture the outcome — feel it. That rehearsal is what you draw on when the real moment comes.', phase: 'rewire', source: 'Visualization Workshop', theme: 'mindset', keepable: true },
  { id: 'RWR-FOO-01', text: 'When you eat off-plan, notice what it\'s really doing for you — hunger, or comfort, reward, boredom. No shame in the answer. Naming food\'s real job is the first move toward changing it.', phase: 'rewire', source: 'Food Relationship Assessment', theme: 'food', keepable: true },
  { id: 'RWR-FOO-02', text: 'Try one lens today: food as fuel for the person you\'re reclaiming — not a reward, not a punishment. A new relationship with food gets built one plate at a time.', phase: 'rewire', source: 'Food Relationship Assessment', theme: 'food', keepable: true },
  { id: 'RWR-FST-01', text: 'Setbacks are part of the process, not proof you failed. The people who make it aren\'t the ones who never slip — they\'re the ones who don\'t let a slip become a slide.', phase: 'rewire', source: 'False Start Protocol', theme: 'setbacks', keepable: true },
  { id: 'RWR-FST-02', text: 'Decide your return move while it\'s calm: the smallest action that counts as clipping back in after a missed day. Not a redemption arc — one rep. Decide it now so the next-day you doesn\'t have to.', phase: 'rewire', source: 'False Start Protocol', theme: 'setbacks', keepable: true },
  { id: 'RWR-STK-01', text: 'Notice how you talk to yourself when you mess up. Would you say it to a friend you respect? Most of us run a coach we\'d never tolerate from anyone else. Hearing it is step one.', phase: 'rewire', source: 'Self-Talk Audit', theme: 'self-talk', keepable: true },
  { id: 'RWR-STK-02', text: 'Take one harsh line and rewrite it true but forgiving. \'I always quit\' becomes \'I\'ve stopped before, and I\'m here again.\' Forgiving yourself isn\'t going soft — it\'s how the change survives a bad day.', phase: 'rewire', source: 'Self-Talk Audit', theme: 'self-talk', keepable: true },
  { id: 'RWR-CHK-01', text: 'Ask honestly: has anything shifted in how you think about your body, your food, or what\'s possible? Even one belief looser than it was is the ground the next stretch of work stands on.', phase: 'rewire', source: 'Rewire Checkpoint', theme: 'mindset', keepable: true },
  { id: 'RWR-CHK-02', text: 'You don\'t have to be \'done\' thinking to start moving. You only have to have shifted the frame enough that the building will hold. That\'s what readiness actually is.', phase: 'rewire', source: 'Rewire Checkpoint', theme: 'mindset', keepable: true },
  { id: 'RBD-FST-01', text: 'The best exercise is the one you\'ll actually do. Walking\'s the most popular for a reason; cycling\'s right behind it. Pick the thing you won\'t talk yourself out of by Wednesday.', phase: 'rebuild', source: 'First Step Assessment', theme: 'movement', keepable: true },
  { id: 'RBD-FST-02', text: 'An honest baseline — how long you can go before it gets hard — isn\'t a judgment. It\'s the only place a foundation holds: where you actually are.', phase: 'rebuild', source: 'First Step Assessment', theme: 'movement', keepable: true },
  { id: 'RBD-7MIN-01', text: 'Some days the whole job is seven minutes. Nobody white-knuckles a full workout from a dead start — but anyone can do seven, and seven is usually enough to remember why you started.', phase: 'rebuild', source: 'The Seven Minutes', theme: 'momentum', keepable: true },
  { id: 'RBD-7MIN-02', text: 'The deal: you only owe seven minutes. Stop after with a clean conscience if you want. Most days you won\'t want to — that\'s not willpower, it\'s momentum, and it\'s on your side now.', phase: 'rebuild', source: 'The Seven Minutes', theme: 'momentum', keepable: true },
  { id: 'RBD-INV-01', text: 'The work nobody sees is the work that holds: water, a little mobility, not sitting for nine hours straight. Shoring up one invisible foundation buys you more than the workout alone.', phase: 'rebuild', source: 'Invisible Foundations Checklist', theme: 'foundations', keepable: true },
  { id: 'RBD-FUEL-01', text: 'A diet isn\'t something you go on — it\'s something you have. The pattern that lasts is the one you can sustain: more real food, less of the processed stuff. One swap you\'d actually keep beats ten you won\'t.', phase: 'rebuild', source: 'Fuel Plan', theme: 'food', keepable: true },
  { id: 'RBD-FUEL-02', text: 'Keeping weight off isn\'t about crash dieting — it\'s about nudging your set point, slowly, like a thermostat. Crash diets fight the thermostat and lose. The slow move is the one that holds.', phase: 'rebuild', source: 'Fuel Plan', theme: 'food', keepable: true },
  { id: 'RBD-MOVE-01', text: 'Aim for the floor first: about 150 minutes of moderate movement a week — roughly thirty minutes, five days. Lock the floor before you chase the ceiling.', phase: 'rebuild', source: 'Movement Menu', theme: 'movement', keepable: true },
  { id: 'RBD-MOVE-02', text: 'A \'yes\' feeds the streak. A \'no\' after a run of yeses is just life — and the next yes is the one that counts most.', phase: 'rebuild', source: 'Movement Menu', theme: 'consistency', keepable: true },
  { id: 'RBD-1KMI-01', text: 'Gary rode 1,052 miles his first year at 250-plus pounds, on flat roads and a trainer. The number was never the point — the consistency it forced was. Pick a total that scares you a little.', phase: 'rebuild', source: 'First 1,000 Miles', theme: 'consistency', keepable: true },
  { id: 'RBD-1KMI-02', text: 'The base gets built in the cold months, on the trainer, when nobody\'s watching. That\'s the part that makes the big day possible. Every small unit is a vote for who you\'re becoming.', phase: 'rebuild', source: 'First 1,000 Miles', theme: 'consistency', keepable: true },
  { id: 'RBD-SLP-01', text: 'You don\'t get stronger during the effort — you get stronger during the recovery, when the body rebuilds. Sleep isn\'t time off from the work. It\'s part of it.', phase: 'rebuild', source: 'Sleep & Recover', theme: 'recovery', keepable: true },
  { id: 'RBD-CHK-01', text: 'Set today\'s numbers next to where you started. Something\'s usually moving — capacity, weight, how the stairs feel. That\'s the measuring stick doing its job.', phase: 'rebuild', source: 'Rebuild Checkpoint', theme: 'progress', keepable: true },
  { id: 'RCL-RDY-01', text: 'Reclaim isn\'t a finish line — it\'s the moment the recovered you starts showing up in the wider world. Are you beginning to feel like the person on your list, even a little? No rush. The Loop comes back around either way.', phase: 'reclaim', source: 'Reclaim Readiness', theme: 'emergence', keepable: true },
  { id: 'RCL-RDY-02', text: 'Reclaiming doesn\'t mean you were broken. It means you\'ve got the agency to direct what comes next — on purpose. Aging well comes down to three things: meaningful activity, close relationships, and a sense of purpose.', phase: 'reclaim', source: 'Reclaim Readiness', theme: 'purpose', keepable: true },
  { id: 'RCL-SUC-01', text: 'Tell the story of one thing you got back — not the metrics, but what it felt like the first time you noticed the old you was back in the room. Saying it out loud makes it real, and easier to defend when doubt returns.', phase: 'reclaim', source: 'Your Success Story', theme: 'emergence', keepable: true },
  { id: 'RCL-ADV-01', text: 'A reclaimed identity needs a proving ground. Pick a real event that scares and excites you — the one that lets you say \'I did this\' when it\'s done. Half the joy is the build-up.', phase: 'reclaim', source: 'Adventure Planning', theme: 'adventure', keepable: true },
  { id: 'RCL-ADV-02', text: 'You don\'t fight conditions on the big day — you prepare in the quiet weeks so the day is a celebration, not a survival. Work backward from the date.', phase: 'reclaim', source: 'Adventure Planning', theme: 'adventure', keepable: true },
  { id: 'RCL-BIG-01', text: 'The Fade shrinks your world; Reclaim widens it back. Where has yours gone small — the places you stopped going, the things you stopped saying yes to? Push one edge back out.', phase: 'reclaim', source: 'Bigger World Audit', theme: 'connection', keepable: true },
  { id: 'RCL-INV-01', text: 'The door opens through relationships, not credentials. Who would you say \'come do this with me\' to? Reaching out to one person — not to coach them, just to share it — is how this becomes a movement instead of a solo act.', phase: 'reclaim', source: 'Invitation Exercise', theme: 'connection', keepable: true },
  { id: 'RCL-INV-02', text: 'The line that lands isn\'t \'you should exercise more.\' It\'s \'I know what you\'re capable of.\' Who in your life needs to hear it from you?', phase: 'reclaim', source: 'Invitation Exercise', theme: 'connection', keepable: true },
  { id: 'RCL-SOC-01', text: 'Belonging beats attending. Social support is one of the strongest predictors of change that sticks — and a real buffer against stress. Where\'s one place you could really show up?', phase: 'reclaim', source: 'Social Connection', theme: 'connection', keepable: true },
  { id: 'RCL-LEG-01', text: 'Imagine writing to someone who\'ll read it later — a kid, a friend, the next person walking through your door. What did you reclaim, and what do you want them to know is still possible in midlife?', phase: 'reclaim', source: 'Legacy Letter', theme: 'legacy', keepable: true },
  { id: 'RCL-LEG-02', text: 'The finish line moves. You\'ll reclaim these, life will shift, and the list will re-form. That\'s not failure — it\'s the design. It\'s why it\'s Grinta for Life. When you\'re ready, you clip back in and go again.', phase: 'reclaim', source: 'Legacy Letter', theme: 'legacy', keepable: true },
  { id: 'HRD-01', text: 'Some days the whole job is just to clip in. Not perfect. In.', phase: 'universal', source: '(Hardiness Beats)', theme: 'hardiness', keepable: true },
  { id: 'HRD-02', text: 'Plenty is out of your hands today. Name one thing that isn\'t — and do that. Control is a muscle.', phase: 'universal', source: '(Hardiness Beats)', theme: 'hardiness', keepable: true },
  { id: 'HRD-03', text: 'Pick one thing today that\'s a little harder than it needs to be — on purpose, because of who it\'s turning you into.', phase: 'universal', source: '(Hardiness Beats)', theme: 'hardiness', keepable: true },
  { id: 'HRD-04', text: 'Missed yesterday? Then today\'s the rep that matters most. The slip isn\'t the story; the return is. Clip back in.', phase: 'universal', source: '(Hardiness Beats)', theme: 'setbacks', keepable: true },
  { id: 'HRD-05', text: 'Keep the reason you started somewhere you\'ll see it. Motivation fades; a reason you can read doesn\'t.', phase: 'universal', source: '(Hardiness Beats)', theme: 'purpose', keepable: true },
  { id: 'HRD-06', text: 'There\'s always a moment everyone\'s struggling — and the one with more Grinta keeps going. That\'s not a feeling. It\'s a decision. Make it once today.', phase: 'universal', source: '(Hardiness Beats)', theme: 'hardiness', keepable: true },
  { id: 'HRD-07', text: 'One off day is a slip. Three is a slide. You\'re allowed the slip — just don\'t let today be day two.', phase: 'universal', source: '(Hardiness Beats)', theme: 'setbacks', keepable: true },
  { id: 'HRD-08', text: 'Reach out to one person in your corner — a check-in, a plan, a \'come do this with me.\' Connection is fuel, and it runs both ways.', phase: 'universal', source: '(Hardiness Beats)', theme: 'connection', keepable: true },
  { id: 'HRD-09', text: 'Is there a stretch effort on your horizon? Without one, the work goes flat. Put one small challenge on the calendar.', phase: 'universal', source: '(Hardiness Beats)', theme: 'purpose', keepable: true },
  { id: 'HRD-10', text: 'If you\'re running the harsh tape about yourself, cut it. Forgiveness isn\'t softness — it\'s how the change survives. One kind, true line, then go.', phase: 'universal', source: '(Hardiness Beats)', theme: 'self-talk', keepable: true },
  { id: 'HRD-11', text: 'Don\'t chase the streak for its own sake. Chase the person it\'s building. If the streak breaks, the person doesn\'t.', phase: 'universal', source: '(Hardiness Beats)', theme: 'consistency', keepable: true },
  { id: 'HRD-12', text: 'Picture the Tuesday a year out if you keep going. Then go do one small thing your future self would thank you for.', phase: 'universal', source: '(Hardiness Beats)', theme: 'vision', keepable: true },
];

const BY_ID: Map<string, Reflection> = new Map(REFLECTIONS.map((r) => [r.id, r]));
export const reflectionById = (id: string): Reflection | undefined => BY_ID.get(id);
