// G4L — Platform & Program Overview, for the internal team.
//
// Built on Cowork's Deck Kit (2026-08-30): the chrome helpers below are hers, unchanged, so this deck sits in the
// same brand system as the tutorial and the funder deck. Edit THIS script, never the .pptx.
//
// EVERY NUMBER IN HERE IS MEASURED, not remembered — see decks/FACTS.md for the command behind each one. Jay's
// standing instruction for this deck was "don't update this from memory, go back thoroughly through what we've
// actually built", and the deck says out loud where a figure is a floor rather than an estimate.
const pptxgen = require('pptxgenjs');
const path = require('path');
const F = require('./facts.json'); // regenerated by `node decks/measure.js`

const p = new pptxgen();
p.layout = 'LAYOUT_WIDE';
const RINGS = path.join(__dirname, 'rings_transparent.png');
const STRIPE = path.join(__dirname, 'stripe_band.png');
const WORDMARK = path.join(__dirname, 'wordmark_navy.png');

// --- Cowork's locked brand tokens + chrome (do not edit) ---------------------------------------------------
const NAVY='374F63', TEAL='3B9495', ORANGE='EC6233', OLIVE='919536', RED='BB2127',
      BODY='3A434B', GREY='5B636B', GREYL='8A929A', LGREY='E8E6E6', OFF='F3F4F5', WHITE='FFFFFF';
const HEAD='Barlow';
const rr = p.ShapeType.roundRect, oval = p.ShapeType.ellipse;
const stripes = (s) => s.addImage({ path: STRIPE, x:0, y:7.15, w:13.333, h:0.35 });
const wordmark = (s) => s.addImage({ path: WORDMARK, x:0.5, y:6.58, w:1.1, h:0.523 });
const pageno = (s,n) => s.addText(String(n), { x:12.25, y:0.3, w:0.75, h:0.32, fontFace:HEAD, color:GREYL, fontSize:13, align:'right', margin:0 });
const chrome = (s,n) => { stripes(s); wordmark(s); if (n) pageno(s,n); };
const title = (s,t,dek) => {
  s.addText(t, { x:0.55, y:0.42, w:11.5, h:0.7, fontFace:HEAD, bold:true, color:NAVY, fontSize:32, align:'left', margin:0 });
  if (dek) s.addText(dek, { x:0.57, y:1.12, w:11.8, h:0.4, fontFace:HEAD, color:GREY, fontSize:17, align:'left', margin:0 });
};
const dot = (s,x,y,d,color,label) => {
  s.addShape(oval, { x, y, w:d, h:d, fill:{color}, line:{width:0} });
  s.addText(String(label), { x, y:y-0.005, w:d, h:d, fontFace:HEAD, bold:true, color:WHITE, fontSize:16, align:'center', valign:'middle', margin:0 });
};
const statCard = (s,x,y,w,big,label,color) => {
  s.addShape(rr, { x, y, w, h:1.5, rectRadius:0.12, fill:{color:OFF}, line:{color:LGREY,width:1} });
  s.addText(big, { x, y:y+0.16, w, h:0.7, fontFace:HEAD, bold:true, color:color||NAVY, fontSize:34, align:'center', margin:0 });
  s.addText(label, { x:x+0.12, y:y+0.88, w:w-0.24, h:0.5, fontFace:HEAD, color:GREY, fontSize:12.5, align:'center', valign:'top', lineSpacingMultiple:1.05, margin:0 });
};

// ============================================================ 1 · cover
let s = p.addSlide(); s.background = { color: WHITE };
s.addImage({ path: RINGS, x:9.0, y:1.55, w:3.25, h:3.25 });
s.addText('PLATFORM & PROGRAM OVERVIEW', { x:0.7, y:2.4, w:7.6, h:0.35, fontFace:HEAD, bold:true, color:TEAL, fontSize:14, charSpacing:2, align:'left', margin:0 });
s.addText('What we built.', { x:0.66, y:2.78, w:8.0, h:1.5, fontFace:HEAD, bold:true, color:NAVY, fontSize:40, align:'left', margin:0 });
s.addText('Twelve weeks, and it is live.', { x:0.7, y:4.35, w:7.6, h:0.5, fontFace:HEAD, color:GREY, fontSize:22, align:'left', margin:0 });
s.addText(`${F.date}   ·   For the internal team   ·   Confidential`, { x:0.7, y:5.05, w:7.8, h:0.35, fontFace:HEAD, italic:true, color:GREYL, fontSize:13, align:'left', margin:0 });
s.addText('© 2026 Adjacent Lab, LLC', { x:9.6, y:6.86, w:3.2, h:0.3, fontFace:HEAD, color:GREYL, fontSize:11, align:'right', margin:0 });
chrome(s, null);

// ============================================================ 2 · since we last saw you
s = p.addSlide(); s.background = { color: WHITE };
title(s, 'Since we last saw you.', 'The platform went from a working prototype to the thing a member actually walks.');
s.addShape(rr, { x:0.6, y:1.72, w:12.13, h:1.15, rectRadius:0.12, fill:{color:NAVY}, line:{width:0} });
s.addText([
  { text:'It is live. ', options:{ bold:true } },
  { text:`Production is on ${F.version}, deployed continuously — ${F.releasesSinceLast} releases in the last two weeks alone. Every member-facing change in this deck is running right now, not planned.`, options:{} },
], { x:0.95, y:1.72, w:11.4, h:1.15, fontFace:HEAD, color:WHITE, fontSize:16, align:'left', valign:'middle', lineSpacingMultiple:1.1, margin:0 });

statCard(s, 0.6,  3.15, 2.85, String(F.sessions),        'Sessions across the four phases', NAVY);
statCard(s, 3.68, 3.15, 2.85, String(F.memberSurfaces),  'member-facing surfaces, all live', TEAL);
statCard(s, 6.76, 3.15, 2.85, String(F.doors),           'Doors in the taxonomy', OLIVE);
statCard(s, 9.84, 3.15, 2.89, String(F.gatedAssets),     'gated assets delivered by the engine', ORANGE);

s.addText('What changed most', { x:0.62, y:4.95, w:12.1, h:0.35, fontFace:HEAD, bold:true, color:NAVY, fontSize:16, align:'left', margin:0 });
const changes = [
  ['Reconnect became four Sessions.', 'It was one unbroken 65-minute conversation with no stopping point. It is now four sittings of 5–25 minutes.'],
  ['Every Session opens on a question.', 'Eight of sixteen used to open on item 1 of a rating scale. A member’s first act is no longer tapping a number.'],
  ['Reclaim got its structure.', 'C1 now runs six revision passes over the member’s own list; C3 sets a week up before it asks for one.'],
];
changes.forEach((c,i) => {
  const y = 5.35 + i*0.55;
  dot(s, 0.62, y, 0.34, [TEAL,ORANGE,RED][i], i+1);
  s.addText([{ text:c[0]+'  ', options:{bold:true, color:NAVY} }, { text:c[1], options:{color:BODY} }],
    { x:1.1, y:y-0.02, w:11.6, h:0.5, fontFace:HEAD, fontSize:13.5, align:'left', valign:'top', lineSpacingMultiple:1.05, margin:0 });
});
chrome(s, 2);

// ============================================================ 3 · the diagram (before / after)
s = p.addSlide(); s.background = { color: WHITE };
title(s, 'The Program, before and after.', 'Every phase is now four Sessions with real boundaries. Turn counts are floors, from an offline walk.');
const PHASES = [
  { name:'Reconnect', before:[['ONE unbroken session','~65 min · IDQ third · no stopping point', NAVY, 4]],
    after:[['R1 Mirror','25 turns · 24 items',TEAL],['R2 Excavation','the Doors board',TEAL],['R3 Drift + Letter','talk only',TEAL],['R4 Check','7 turns · 6 items',OLIVE]] },
  { name:'Rewire', before:[['W1','8 turns',NAVY,1],['W2','6 turns',NAVY,1],['W3','8 turns',NAVY,1],['W4 Check','opens on item 1',NAVY,1]],
    after:[['W1 Lies','8 turns',TEAL],['W2 Picture','6 turns',TEAL],['W3 Protocol','8 turns',TEAL],['W4 Check','7 turns · 6 items',OLIVE]] },
  { name:'Rebuild', before:[['B1','12 items, nothing else',ORANGE,1],['B2','24 items, nothing else',ORANGE,1],['B3 Pilot','30 turns',NAVY,1],['B4 Check','opens on item 1',ORANGE,1]],
    after:[['B1 Your Why','19 turns · 12 items',TEAL],['B2 Strengths','31 turns · 24 items',TEAL],['B3 Pilot','30 turns',NAVY],['B4 Check','7 turns · 6 items',OLIVE]] },
  { name:'Reclaim', before:[['C1','one open conversation',RED,1],['C2','20 ratings, then close',ORANGE,1],['C3','one open conversation',RED,1],['C4 Check','opens on item 1',ORANGE,1]],
    after:[['C1 Forward','6 revision passes',TEAL],['C2 Bigger World','~47 turns · 20 items',TEAL],['C3 Quality','4 stages',TEAL],['C4 Check','7 turns · 6 items',OLIVE]] },
];
s.addText('BEFORE — 27 AUGUST', { x:0.6, y:1.62, w:5.9, h:0.28, fontFace:HEAD, bold:true, color:GREYL, fontSize:11.5, charSpacing:1.5, margin:0 });
s.addText('AFTER — SHIPPED', { x:6.95, y:1.62, w:5.9, h:0.28, fontFace:HEAD, bold:true, color:TEAL, fontSize:11.5, charSpacing:1.5, margin:0 });
s.addShape(p.ShapeType.line, { x:6.78, y:1.6, w:0, h:4.55, line:{ color:LGREY, width:1 } });
PHASES.forEach((ph, r) => {
  const y = 1.98 + r*1.13;
  s.addText(ph.name, { x:0.6, y, w:5.9, h:0.24, fontFace:HEAD, bold:true, color:NAVY, fontSize:11, margin:0 });
  const draw = (cards, x0, wTotal) => {
    const n = cards.length, gap = 0.08, w = (wTotal - gap*(n-1)) / n;
    cards.forEach((c, i) => {
      const span = c[3] || 1;
      const cw = span > 1 ? wTotal : w;
      s.addShape(rr, { x:x0 + i*(w+gap), y:y+0.26, w:cw, h:0.62, rectRadius:0.07, fill:{color:c[2]}, line:{width:0} });
      s.addText([{ text:c[0], options:{bold:true, fontSize:9.5, breakLine:true} }, { text:c[1], options:{fontSize:7.5} }],
        { x:x0 + i*(w+gap) + 0.06, y:y+0.28, w:cw-0.12, h:0.58, fontFace:HEAD, color:WHITE, align:'left', valign:'middle', lineSpacingMultiple:0.95, margin:0 });
    });
  };
  draw(ph.before, 0.6, 5.9);
  draw(ph.after, 6.95, 5.85);
});
s.addShape(rr, { x:0.6, y:6.5, w:12.13, h:0.5, rectRadius:0.09, fill:{color:OFF}, line:{color:TEAL, width:1} });
s.addText([
  { text:'The one change that runs through all four:  ', options:{bold:true, color:NAVY} },
  { text:'eight of sixteen Sessions opened on item 1 of a rating scale. All sixteen now open with a frame and one open question — the instrument arrives after the member has said something.', options:{color:BODY} },
], { x:0.85, y:6.5, w:11.7, h:0.5, fontFace:HEAD, fontSize:12, align:'left', valign:'middle', margin:0 });
chrome(s, 3);

// ============================================================ 4 · what a member walks
s = p.addSlide(); s.background = { color: WHITE };
title(s, 'What a member actually walks.', 'One conversation engine, four phases, sixteen Sessions — plus the intake that starts it.');
const walk = [
  ['Intake', 'A real conversation, not a form. It captures who they were, the Fade, the Doors it came through, and the Reclaim List — the outcomes the whole program then routes on.', NAVY],
  ['Reconnect', 'Four short sittings. The ID Score is taken first, then the Doors board, then the drift and the Legacy Letter, then a Checkpoint.', TEAL],
  ['Rewire · Rebuild', 'Mind and body, dosed per member rather than run in sequence. Rewire is the lightest phase; Rebuild is the heaviest — B2 alone is 24 self-ratings inside a 31-turn conversation.', OLIVE],
  ['Reclaim', 'The outcome state. C1 revises the member’s own list in six passes; C2 is the longest Session in the program; C3 defines what a day worth having looks like.', ORANGE],
];
walk.forEach((w, i) => {
  const y = 1.85 + i*1.22;
  s.addShape(rr, { x:0.6, y, w:2.5, h:1.05, rectRadius:0.1, fill:{color:w[2]}, line:{width:0} });
  s.addText(w[0], { x:0.7, y, w:2.3, h:1.05, fontFace:HEAD, bold:true, color:WHITE, fontSize:17, align:'left', valign:'middle', margin:0 });
  s.addText(w[1], { x:3.3, y:y+0.05, w:9.4, h:0.95, fontFace:HEAD, color:BODY, fontSize:14, align:'left', valign:'middle', lineSpacingMultiple:1.1, margin:0 });
});
s.addText('The Companion is present in all of it — it is the product, not a feature bolted to it.', { x:0.62, y:6.75, w:12.1, h:0.35, fontFace:HEAD, italic:true, color:GREYL, fontSize:12.5, margin:0 });
chrome(s, 4);

// ============================================================ 5 · governance in code
s = p.addSlide(); s.background = { color: WHITE };
title(s, 'The rules are in the code, not the prompt.', 'Governance a model could talk its way around is not governance.');
const gov = [
  ['Crisis routing is always on.', 'Distress is detected before the model is ever consulted, and answers with the 988 Lifeline. It sits at the top of the shared turn handler, so every conversational surface inherits it.'],
  ['It never invents a Door.', 'A member’s own plain statement outranks anything we infer about them. A prospect who says nothing pulled him away is never assigned a Door he did not describe.'],
  ['It never drops what they gave you.', 'The Reclaim List is the artifact everything routes on. Nothing in the capture path may discard a want — a rule now enforced by a test that fails if any code path does.'],
  ['It is always disclosed.', 'The member knows they are talking with AI before the first conversation, and can stop at any time.'],
];
gov.forEach((g,i) => {
  const x = 0.6 + (i%2)*6.15, y = 1.8 + Math.floor(i/2)*2.35;
  s.addShape(rr, { x, y, w:5.95, h:2.1, rectRadius:0.12, fill:{color:OFF}, line:{color:LGREY, width:1} });
  s.addText(g[0], { x:x+0.3, y:y+0.22, w:5.35, h:0.5, fontFace:HEAD, bold:true, color:[NAVY,TEAL,ORANGE,OLIVE][i], fontSize:17, align:'left', margin:0 });
  s.addText(g[1], { x:x+0.3, y:y+0.75, w:5.35, h:1.2, fontFace:HEAD, color:BODY, fontSize:13, align:'left', valign:'top', lineSpacingMultiple:1.12, margin:0 });
});
chrome(s, 5);

// ============================================================ 6 · what it runs on
s = p.addSlide(); s.background = { color: WHITE };
title(s, 'What it runs on.', 'Build the differentiated core; integrate the commodities.');
const stack = [
  ['The core we built', 'The conversation engine, the capture contracts, the instruments and their scoring, the Playbook, the Community. Framework-free and testable against a local Postgres.', TEAL],
  ['The platform', `Next.js ${F.next} · React ${F.react} · TypeScript ${F.typescript}. Postgres on Supabase in production, an embedded Postgres for tests, so the suite runs offline and deterministically.`, NAVY],
  ['The model', `Anthropic’s Claude via the official SDK (${F.sdk}). Prompt caching on the highest-volume paths. The engine owns structure; the model owns words.`, OLIVE],
  ['Integrated, not rebuilt', 'Stripe for payments, HubSpot for lifecycle, Tovuti for course delivery. Fifteen dependencies in total — the surface area is deliberately small.', ORANGE],
];
stack.forEach((c,i) => {
  const y = 1.8 + i*1.3;
  s.addShape(rr, { x:0.6, y, w:2.9, h:1.12, rectRadius:0.1, fill:{color:c[2]}, line:{width:0} });
  s.addText(c[0], { x:0.75, y, w:2.6, h:1.12, fontFace:HEAD, bold:true, color:WHITE, fontSize:15.5, align:'left', valign:'middle', margin:0 });
  s.addText(c[1], { x:3.7, y:y+0.05, w:9.0, h:1.0, fontFace:HEAD, color:BODY, fontSize:13.5, align:'left', valign:'middle', lineSpacingMultiple:1.1, margin:0 });
});
chrome(s, 6);

// ============================================================ 7 · how it is built
s = p.addSlide(); s.background = { color: WHITE };
title(s, 'How it is built.', 'Human judgment, AI throughput — with the judgment written down first.');
statCard(s, 0.6,  1.85, 2.85, F.tests.toLocaleString(), 'automated checks, run before every change', NAVY);
statCard(s, 3.68, 1.85, 2.85, String(F.testFiles),      'test files', TEAL);
statCard(s, 6.76, 1.85, 2.85, String(F.migrations),     'database migrations, applied in order', OLIVE);
statCard(s, 9.84, 1.85, 2.89, F.sourceLines.toLocaleString(), 'lines of application code', ORANGE);
const how = [
  ['Spec-driven.', 'Greg’s science documents and the governance framework are the source. Where a Session’s shape is his, the code cites the document and the page.'],
  ['Tested against real failures.', 'When a member hits a bug, the transcript becomes a fixture. The suite replays real conversations offline, so a fix can be proven not to break the others.'],
  ['A checker for our own worst habit.', 'The recurring defect here is a rule that exists and never runs — a guard nothing calls, a decision that never took effect. A tool now hunts them mechanically and fails the build if the count grows.'],
];
how.forEach((h,i) => {
  const y = 3.7 + i*1.02;
  dot(s, 0.62, y+0.04, 0.42, [NAVY,TEAL,ORANGE][i], i+1);
  s.addText(h[0], { x:1.25, y, w:11.4, h:0.34, fontFace:HEAD, bold:true, color:NAVY, fontSize:16.5, align:'left', margin:0 });
  s.addText(h[1], { x:1.25, y:y+0.33, w:11.4, h:0.62, fontFace:HEAD, color:BODY, fontSize:13.5, align:'left', valign:'top', lineSpacingMultiple:1.08, margin:0 });
});
chrome(s, 7);

// ============================================================ 8 · the effort
s = p.addSlide(); s.background = { color: WHITE };
title(s, 'What it took to build.', 'Measured from the repository, not estimated.');
statCard(s, 0.6,  1.85, 2.85, `${F.hours}`,            'hours of build time (a floor — see note)', NAVY);
statCard(s, 3.68, 1.85, 2.85, F.commits.toLocaleString(), 'commits', TEAL);
statCard(s, 6.76, 1.85, 2.85, String(F.activeDays),    'days with work committed', OLIVE);
statCard(s, 9.84, 1.85, 2.89, String(F.weeks),         'calendar weeks, first commit to today', ORANGE);
s.addShape(rr, { x:0.6, y:3.65, w:12.13, h:1.35, rectRadius:0.12, fill:{color:NAVY}, line:{width:0} });
s.addText([
  { text:'How the hours are counted.  ', options:{bold:true} },
  { text:`Commits are grouped into working sessions — a gap of more than ninety minutes ends one — and each session is credited its span plus twenty minutes. That yields ${F.workSessions} sessions, a median of ${F.medianHours} hours and a longest of ${F.longestHours}. It is a FLOOR: it cannot see planning before a session’s first commit, reading, or any day that ended without one.`, options:{} },
], { x:0.95, y:3.65, w:11.4, h:1.35, fontFace:HEAD, color:WHITE, fontSize:14, align:'left', valign:'middle', lineSpacingMultiple:1.12, margin:0 });
s.addText('For scale: that is roughly a third of a person-year of engineering, delivered by one founder working with an AI pair — and it is why the platform is a purpose-built product rather than AI layered onto a template.',
  { x:0.62, y:5.25, w:12.1, h:0.9, fontFace:HEAD, color:BODY, fontSize:15, align:'left', valign:'top', lineSpacingMultiple:1.12, margin:0 });
chrome(s, 8);

// ============================================================ 9 · where it stands
s = p.addSlide(); s.background = { color: WHITE };
title(s, 'Where it stands.', 'Honest about what is done, what is being tested, and what is still open.');
const cols = [
  ['Done and live', TEAL, ['All four phases, conversational end to end','All sixteen Sessions with their own structure','The Companion across every phase','The Community, native on our own stack','Intake that no longer turns anyone away']],
  ['In test now', ORANGE, ['Donna is walking the current build','A six-persona live evaluation runs against the real model','The onboarding capture path, hardened this week']],
  ['Still open', RED, ['One known capture miss on a Door','The 60-day Loop rule — needs Greg','Charter onboarding for the first members']],
];
cols.forEach((c,i) => {
  const x = 0.6 + i*4.13;
  s.addShape(rr, { x, y:1.8, w:3.85, h:0.6, rectRadius:0.1, fill:{color:c[1]}, line:{width:0} });
  s.addText(c[0], { x, y:1.8, w:3.85, h:0.6, fontFace:HEAD, bold:true, color:WHITE, fontSize:17, align:'center', valign:'middle', margin:0 });
  c[2].forEach((t,j) => {
    const y = 2.6 + j*0.86;
    s.addShape(rr, { x, y, w:3.85, h:0.74, rectRadius:0.09, fill:{color:OFF}, line:{color:LGREY,width:1} });
    s.addText(t, { x:x+0.2, y, w:3.45, h:0.74, fontFace:HEAD, color:BODY, fontSize:12.5, align:'left', valign:'middle', lineSpacingMultiple:1.05, margin:0 });
  });
});
chrome(s, 9);

// ============================================================ 10 · close
s = p.addSlide(); s.background = { color: NAVY };
s.addImage({ path: RINGS, x:9.6, y:1.5, w:3.0, h:3.0 });
s.addText('It is real, and it is running.', { x:0.8, y:2.5, w:8.4, h:1.0, fontFace:HEAD, bold:true, color:WHITE, fontSize:36, align:'left', margin:0 });
s.addText('Twelve weeks from first commit to a program a member can walk end to end — measured, tested, and honest about what is not finished. What we need from you now is your read on it, and the questions your networks will ask.',
  { x:0.82, y:3.7, w:8.2, h:1.8, fontFace:HEAD, color:'D8DEE3', fontSize:17, align:'left', valign:'top', lineSpacingMultiple:1.15, margin:0 });
stripes(s); wordmark(s);

const OUT = path.join(process.env.HOME, 'Desktop', 'New_Decks', 'G4L-Platform-and-Program-Overview-Aug-30-2026.pptx');
p.writeFile({ fileName: OUT }).then(() => console.log('WROTE ' + OUT));
